services:
  api:
    container_name: leaderboard-api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    env_file:
      - ./api/.env
    volumes:
      - ./shared:/shared
    develop:
      watch:
        - action: sync
          path: ./api/src
          target: /app/src
          initial_sync: true
        - action: rebuild
          path: ./api/package.json
  web:
    container_name: leaderboard-client
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    env_file:
      - ./web/.env
    volumes:
      - ./shared:/shared
    develop:
      watch:
        - action: sync
          path: ./web/src
          target: /app/src
          ignore:
            - stores/
            - router.ts
          initial_sync: true
        - action: sync+restart
          path: ./web/src/router.ts
          target: ./web/src/router.ts
          initial_sync: true
        - action: sync+restart
          path: ./web/src/stores
          target: /app/src/stores
          initial_sync: true
        - action: rebuild
          path: ./web/package.json
  mongodb:
    container_name: leaderboard-db
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
