services:
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    develop:
      watch:
        - action: sync
          path: ./api/src
          target: /app/src
  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    develop:
      watch:
        - action: sync
          path: ./web/src
          target: /app/src
        - action: rebuild
          path: ./web/package.json
  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
